spring.application.name=vehicle-rental-app
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://18.189.195.73:8081/realms/vehiclerentalrealm

spring.data.mongodb.uri=mongodb+srv://root:root@vra.b3tm8ta.mongodb.net/vra?retryWrites=true&w=majority&appName=vra

app.data.seed=false
